title: Cactus
description: ğŸŒµ Indoor WiFi-connected temperature and humidity sensor ğŸ¶
url: "https://hutscape.com/cactus"
parent: "https://hutscape.com"
markdown: kramdown
permalink: /:title
youtube: https://www.youtube.com/user/sweska/videos
github:
  repository_url: https://github.com/hutscape/cactus
  raw_content_url: https://raw.githubusercontent.com/hutscape/cactus/master
exclude: ["datasheets", "Gemfile", "Gemfile.lock", "contributing.md", "Makefile", "readme.md", "test", "scripts", "firmware"]
include: ["_data"]
