title: Cactus
description: ğŸŒµ Measure humidity in kitchen cupboards to keep food fresh ğŸ¶
url: "https://hutscape.com/cactus"
markdown: kramdown
permalink: /:title
google_analytics: UA-XXXXX-Y
github:
  repository_url: https://github.com/hutscape/cactus
exclude: ["datasheets", "Gemfile", "Gemfile.lock", "contributing.md", "Makefile", "readme.md", "test", "hardware", "scripts", "firmware"]
include: ["_data"]
